// Data array
export const data = [
  {
    id: 1,
    nombre: "Semana del Financiero",
    sentimiento: "Negativo",
    cuentasCreadas: 1200,
    estatus: "Activo",
  },
  {
    id: 2,
    nombre: "Promoción de Verano",
    sentimiento: "Positivo",
    cuentasCreadas: 1500,
    estatus: "Pausado",
  },
  {
    id: 3,
    nombre: "Ventas de Invierno",
    sentimiento: "Neutral",
    cuentasCreadas: 1100,
    estatus: "Activo",
  },
  {
    id: 4,
    nombre: "Oferta de Otoño",
    sentimiento: "Positivo",
    cuentasCreadas: 1350,
    estatus: "Activo",
  },
  {
    id: 5,
    nombre: "Black Friday",
    sentimiento: "Negativo",
    cuentasCreadas: 2300,
    estatus: "Pausado",
  },
  {
    id: 6,
    nombre: "Cyber Monday",
    sentimiento: "Positivo",
    cuentasCreadas: 1700,
    estatus: "Activo",
  },
  {
    id: 7,
    nombre: "Día de San Valentín",
    sentimiento: "Neutral",
    cuentasCreadas: 950,
    estatus: "Activo",
  },
  {
    id: 8,
    nombre: "Semana del Consumidor",
    sentimiento: "Positivo",
    cuentasCreadas: 2100,
    estatus: "Activo",
  },
  {
    id: 9,
    nombre: "Promoción de Pascua",
    sentimiento: "Negativo",
    cuentasCreadas: 1300,
    estatus: "Pausado",
  },
  {
    id: 10,
    nombre: "Festival de Verano",
    sentimiento: "Positivo",
    cuentasCreadas: 1750,
    estatus: "Activo",
  },
  {
    id: 11,
    nombre: "Regreso a Clases",
    sentimiento: "Positivo",
    cuentasCreadas: 1900,
    estatus: "Activo",
  },
  {
    id: 12,
    nombre: "Descuentos Navideños",
    sentimiento: "Neutral",
    cuentasCreadas: 1600,
    estatus: "Pausado",
  },
  {
    id: 13,
    nombre: "Descuentos de Fin de Año",
    sentimiento: "Positivo",
    cuentasCreadas: 2500,
    estatus: "Activo",
  },
  {
    id: 14,
    nombre: "Descuentos para el Buen Fin",
    sentimiento: "Positivo",
    cuentasCreadas: 1750,
    estatus: "Activo",
  },
  {
    id: 15,
    nombre: "Descuentos del Día del Padre",
    sentimiento: "Neutral",
    cuentasCreadas: 1300,
    estatus: "Activo",
  },
  {
    id: 16,
    nombre: "Promoción del Día de la Madre",
    sentimiento: "Positivo",
    cuentasCreadas: 2000,
    estatus: "Pausado",
  },
  {
    id: 17,
    nombre: "Descuentos de Halloween",
    sentimiento: "Negativo",
    cuentasCreadas: 1150,
    estatus: "Activo",
  },
  {
    id: 18,
    nombre: "Descuentos de Año Nuevo",
    sentimiento: "Positivo",
    cuentasCreadas: 2600,
    estatus: "Activo",
  },
  {
    id: 19,
    nombre: "Descuentos de Primavera",
    sentimiento: "Neutral",
    cuentasCreadas: 1400,
    estatus: "Activo",
  },
  {
    id: 20,
    nombre: "Descuentos del Día del Niño",
    sentimiento: "Positivo",
    cuentasCreadas: 1850,
    estatus: "Pausado",
  },
  {
    id: 21,
    nombre: "Lanzamiento del Producto X",
    sentimiento: "Negativo",
    cuentasCreadas: 900,
    estatus: "Activo",
  },
  {
    id: 22,
    nombre: "Promoción de Primavera",
    sentimiento: "Positivo",
    cuentasCreadas: 1600,
    estatus: "Pausado",
  },
  {
    id: 23,
    nombre: "Oferta de Fin de Semana",
    sentimiento: "Neutral",
    cuentasCreadas: 1000,
    estatus: "Activo",
  },
];
